version: '3.4'

services:
  tor-ip-changer:
    container_name: tor-changer
    build:
      context: .
      dockerfile: Dockerfile
    # environment:
      # - DISPLAY=${DISPLAY:-:0.0}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      - "9050:9050"
      - "14999:14999"         #uncomment if you need api
    command: "ipchanger -p -a 99999 -u -g -d -n -m 2"        #change to "ipchanger -p" if you need api
    healthcheck:
      test: curl -x socks5h://localhost:9050 http://checkip.amazonaws.com || exit 1
      interval: 20s
      start_period: 30s